version: '3.8'
services:
  web:
    build:
      context: ./webapp
    ports:
      - "8000:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
      - ./webapp/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - engine
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gymgenius
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gymgenius_dev
    ports:
      - "5432:5432"
  engine:
    build:
      context: ./engine
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 "app:app"
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: