version: '3.8'
services:
  web:
    build:
      context: ./webapp
    ports:
      - "8000:80"
    volumes:
      - ./webapp:/usr/share/nginx/html
      - ./webapp/default.conf:/etc/nginx/conf.d/default.conf # Added this line
    depends_on:
      - db
      - engine
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gymgenius
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gymgenius_dev
    ports:
      - "5432:5432"
  engine:
    build:
      context: ./engine
    ports:
      - "5000:5000"
    volumes:
      - ./engine:/app
    depends_on: # Added redis here
      - db
      - redis
  redis: # Added redis service
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: # Added redis_data volume
