version: '3.8'
services:
  web:
    build: ./webapp # Assuming webapp will be in ./webapp
    ports:
      - "8000:8000"
    volumes:
      - ./webapp:/app
    depends_on:
      - db
      - engine
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gymgenius
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gymgenius_dev
    ports:
      - "5432:5432"
  engine:
    build: ./engine # Assuming engine will be in ./engine
    ports:
      - "5000:5000"
    volumes:
      - ./engine:/app

volumes:
  postgres_data:
